/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kasir;

import javax.swing.JOptionPane;

/**
 *
 * @author Win10
 */
public class aplikasi_kasir extends javax.swing.JFrame {

    /**
     * Creates new form aplikasi_kasir
     */
    public aplikasi_kasir() {
        initComponents();
        rdgcarabayar.add(rbcash);
        rdgcarabayar.add(rbbca);
        rdgcarabayar.add(rbmandiri);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgcarabayar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chksoto = new javax.swing.JCheckBox();
        chksate = new javax.swing.JCheckBox();
        chkjeruk = new javax.swing.JCheckBox();
        chkteh = new javax.swing.JCheckBox();
        txtsoto = new javax.swing.JTextField();
        txtsate = new javax.swing.JTextField();
        txtjeruk = new javax.swing.JTextField();
        txtteh = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        rbcash = new javax.swing.JRadioButton();
        rbbca = new javax.swing.JRadioButton();
        rbmandiri = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lbltotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblcarabayar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("WARUNG TEGAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("MENU");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("QUALITY");

        chksoto.setForeground(new java.awt.Color(0, 102, 102));
        chksoto.setMnemonic('S');
        chksoto.setText("SOTO : Rp. 15000");
        chksoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksotoActionPerformed(evt);
            }
        });

        chksate.setForeground(new java.awt.Color(0, 102, 102));
        chksate.setMnemonic('a');
        chksate.setText("SATE : Rp. 20000");
        chksate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksateActionPerformed(evt);
            }
        });

        chkjeruk.setForeground(new java.awt.Color(0, 102, 102));
        chkjeruk.setMnemonic('E');
        chkjeruk.setText("Es Jeruk : Rp. 7000");
        chkjeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkjerukActionPerformed(evt);
            }
        });

        chkteh.setForeground(new java.awt.Color(0, 102, 102));
        chkteh.setMnemonic('T');
        chkteh.setText("Es Teh Manis : Rp. 5000");
        chkteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chktehActionPerformed(evt);
            }
        });

        txtsoto.setEditable(false);
        txtsoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsoto.setForeground(new java.awt.Color(0, 102, 102));
        txtsoto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsoto.setText("0");

        txtsate.setEditable(false);
        txtsate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsate.setForeground(new java.awt.Color(0, 102, 102));
        txtsate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsate.setText("0");

        txtjeruk.setEditable(false);
        txtjeruk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtjeruk.setForeground(new java.awt.Color(0, 102, 102));
        txtjeruk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtjeruk.setText("0");

        txtteh.setEditable(false);
        txtteh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtteh.setForeground(new java.awt.Color(0, 102, 102));
        txtteh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtteh.setText("0");
        txtteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttehActionPerformed(evt);
            }
        });

        rbcash.setText("Cash");
        rbcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcashActionPerformed(evt);
            }
        });

        rbbca.setText("BCA Card");

        rbmandiri.setText("Mandiri Card");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbmandiri, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbcash, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbbca, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbcash)
                .addGap(6, 6, 6)
                .addComponent(rbbca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbmandiri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbltotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(0, 102, 102));
        lbltotal.setText("Rp. 0");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblcarabayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcarabayar.setForeground(new java.awt.Color(0, 102, 102));
        lblcarabayar.setText("CARA BAYAR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("CARA BAYAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chkteh)
                        .addComponent(chkjeruk, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chksate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chksoto, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjeruk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtteh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblcarabayar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chksoto)
                    .addComponent(txtsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chksate)
                    .addComponent(txtsate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkjeruk)
                    .addComponent(txtjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkteh)
                    .addComponent(txtteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltotal)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addComponent(lblcarabayar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chksotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksotoActionPerformed
        // TODO add your handling code here:
        if (chksoto.isSelected()){
            txtsoto.setEditable(true);
            txtsoto.setText("1");
        }
            else {
            txtsoto.setEditable(false);
            txtsoto.setText("0");
        }
    }//GEN-LAST:event_chksotoActionPerformed

    private void txttehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttehActionPerformed
    
    }//GEN-LAST:event_txttehActionPerformed

    private void chksateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksateActionPerformed
        // TODO add your handling code here:
        if (chksate.isSelected()){
            txtsate.setEditable(true);
            txtsate.setText("1");
        }
            else {
            txtsate.setEditable(false);
            txtsate.setText("0");
        }
    }//GEN-LAST:event_chksateActionPerformed

    private void chkjerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkjerukActionPerformed
        // TODO add your handling code here:
        if (chkjeruk.isSelected()){
            txtjeruk.setEditable(true);
            txtjeruk.setText("1");
        }
            else {
            txtjeruk.setEditable(false);
            txtjeruk.setText("0");
        }
        
    }//GEN-LAST:event_chkjerukActionPerformed

    private void chktehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chktehActionPerformed
        // TODO add your handling code here:
        if (chkteh.isSelected()){
            txtteh.setEditable(true);
            txtteh.setText("1");
        }
            else {
            txtteh.setEditable(false);
            txtteh.setText("0");
        }
        
    }//GEN-LAST:event_chktehActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chksoto.setSelected(false);
        chksate.setSelected(false);
        chkjeruk.setSelected(false);
        chkteh.setSelected(false);
        
        txtsoto.setText("0");
        txtsate.setText("0");
        txtjeruk.setText("0");
        txtteh.setText("0");
        
        txtsoto.setEditable(false);
        txtsate.setEditable(false);
        txtteh.setEditable(false);
        txtjeruk.setEditable(false);
        
        lbltotal.setText("Rp. 0");
        lblcarabayar.setText("CARA BAYAR");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean IDataOke = true;
        
        if (chksoto.isSelected()&& txtsoto.getText()== "")
            IDataOke = false;
        if (chksate.isSelected()&& txtsate.getText()== "")
            IDataOke = false;
        if (chkjeruk.isSelected()&& txtjeruk.getText()== "")
            IDataOke = false;
        if (chkteh.isSelected()&& txtteh.getText()== "")
            IDataOke = false;
        
        if(!IDataOke){
            JOptionPane.showMessageDialog(this, "Data Dilengkapi Terlebih dahulu");
            
        } else {
            int nsoto = Integer.parseInt(txtsoto.getText());
            int nsate = Integer.parseInt(txtsate.getText());
            int nteh = Integer.parseInt(txtteh.getText());
            int njeruk = Integer.parseInt(txtjeruk.getText());
            
            int ntotal = (15000*nsoto) + (20000*nsate) + (7000*njeruk) + (6500*nteh);
            lbltotal.setText("Rp. "+ntotal);
            
            if (rbcash.isSelected())
                lblcarabayar.setText(rbcash.getActionCommand());
            if (rbbca.isSelected())
                lblcarabayar.setText(rbbca.getActionCommand());
            if (rbmandiri.isSelected())
                lblcarabayar.setText(rbmandiri.getActionCommand());
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasi_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasi_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasi_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasi_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasi_kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkjeruk;
    private javax.swing.JCheckBox chksate;
    private javax.swing.JCheckBox chksoto;
    private javax.swing.JCheckBox chkteh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblcarabayar;
    private javax.swing.JLabel lbltotal;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton rbbca;
    private javax.swing.JRadioButton rbcash;
    private javax.swing.JRadioButton rbmandiri;
    private javax.swing.ButtonGroup rdgcarabayar;
    private javax.swing.JTextField txtjeruk;
    private javax.swing.JTextField txtsate;
    private javax.swing.JTextField txtsoto;
    private javax.swing.JTextField txtteh;
    // End of variables declaration//GEN-END:variables
}
