/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hitung_gaji;

/**
 *
 * @author Win10
 */
public class hitung_gaji1 extends javax.swing.JFrame {

    /**
     * Creates new form hitung_gaji1
     */
    public hitung_gaji1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        karya = new javax.swing.JTextField();
        txtjmlanak = new javax.swing.JTextField();
        txtnip = new javax.swing.JTextField();
        txttunjangkes = new javax.swing.JTextField();
        txtjmlhari = new javax.swing.JTextField();
        txttransport = new javax.swing.JTextField();
        txtpendapatan = new javax.swing.JTextField();
        txtpinjam = new javax.swing.JTextField();
        txttake = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtpegawai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("gaji");

        jLabel2.setText("nama karyawan");

        jLabel3.setText("nip");

        jLabel4.setText("jumlah Anak");

        jLabel5.setText("tujangan kesehatan");

        jLabel6.setText("jumlah hari");

        jLabel7.setText("transport");

        jLabel8.setText("pendapatan");

        jLabel9.setText("pinjaman koprasi");

        jLabel10.setText("take home");

        txtjmlanak.setText("0");
        txtjmlanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlanakActionPerformed(evt);
            }
        });

        txttunjangkes.setEditable(false);
        txttunjangkes.setText("0");

        txtjmlhari.setText("0");
        txtjmlhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlhariActionPerformed(evt);
            }
        });

        txttransport.setEditable(false);
        txttransport.setText("0");

        txtpendapatan.setEditable(false);
        txtpendapatan.setText("0");
        txtpendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpendapatanActionPerformed(evt);
            }
        });

        txtpinjam.setText("0");
        txtpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpinjamActionPerformed(evt);
            }
        });

        txttake.setEditable(false);
        txttake.setText("0");

        jButton2.setText("clear");

        txtpegawai.setEditable(false);
        txtpegawai.setText("800000");

        jLabel11.setText("tujangan pegawai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addComponent(jLabel10))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtjmlanak)
                            .addComponent(txttunjangkes)
                            .addComponent(txtnip)
                            .addComponent(txtjmlhari)
                            .addComponent(txttransport)
                            .addComponent(txtpendapatan)
                            .addComponent(txtpinjam)
                            .addComponent(karya)
                            .addComponent(txttake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpegawai, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButton2)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(karya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtjmlanak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttunjangkes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtjmlhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txttake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpendapatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpendapatanActionPerformed

    private void txtjmlanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlanakActionPerformed
        // TODO add your handling code here:
        int jmlanak = Integer.parseInt(txtjmlanak.getText());
        int jml =80000;
        int tunjang;
        tunjang = jmlanak*jml;
        txttunjangkes.setText(""+tunjang);
    }//GEN-LAST:event_txtjmlanakActionPerformed

    private void txtjmlhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlhariActionPerformed
        // TODO add your handling code here:
        int jmlhari = Integer.parseInt(txtjmlhari.getText());
        int pegawai = Integer.parseInt(txtpegawai.getText());
        int txtkes = Integer.parseInt(txttunjangkes.getText());
        int jml =30000;
        int pendapat;
        int transport;
        transport = jmlhari*jml;
        txttransport.setText(""+transport);
        int txtport = Integer.parseInt(txttransport.getText());
        pendapat = pegawai + txtkes + txtport;
        txtpendapatan.setText(""+pendapat);
        
    }//GEN-LAST:event_txtjmlhariActionPerformed

    private void txtpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpinjamActionPerformed
        // TODO add your handling code here:
        int pinjam = Integer.parseInt(txtpinjam.getText());
        int pendapat = Integer.parseInt(txtpendapatan.getText());
        int take;
        take = pendapat - pinjam;
        txttake.setText(""+take);
    }//GEN-LAST:event_txtpinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitung_gaji1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitung_gaji1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitung_gaji1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitung_gaji1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hitung_gaji1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField karya;
    private javax.swing.JTextField txtjmlanak;
    private javax.swing.JTextField txtjmlhari;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpegawai;
    private javax.swing.JTextField txtpendapatan;
    private javax.swing.JTextField txtpinjam;
    private javax.swing.JTextField txttake;
    private javax.swing.JTextField txttransport;
    private javax.swing.JTextField txttunjangkes;
    // End of variables declaration//GEN-END:variables
}
